version: "3.8"
services:
  frontend:
    deploy:
      replicas: 3
    build: ./frontend
    image: ${DOCKER_HUB_CREDS_USR}/retro_video_games-frontend:red
    container_name: retro_video_games_frontend
    ports:
    - target: 5000
      published: 80
  backend:
    deploy:
      replicas: 3
    build: ./backend
    image: ${DOCKER_HUB_CREDS_USR}/retro_video_games-backend:latest
    container_name: retro_video_games_backend
    environment:
      DATABASE_URI:
      CREATE_SCHEMA:
    ports:
    - target: 5000
      published: 5000